sonar.projectKey=pixelopscloud_attendease-app
sonar.organization=pixelopscloud
sonar.sources=backend/src,frontend
sonar.exclusions=**/node_modules/**,**/*.test.js
sonar.scanner.internal.isCacheEnabled=false
